CREATE DATABASE EMPLOYEE
USE EMPLOYEE;
EMPLOYEE Database ER Diagram:

+----------------+          +---------------+
|    emp_record  |          |  Proj_table   |
+----------------+          +---------------+
| EMP_ID (PK)    |          | PROJECT_ID (PK)|
| FIRST_NAME     |1       * | PROJ_NAME     |
| LAST_NAME      |-------|  | DOMAIN        |
| GENDER         |          | START_DATE    |
| ROLE           |          | CLOSURE_DATE  |
| DEPT           |          | DEV_QTR       |
| EXP            |          | STATUS        |
| COUNTRY        |          +---------------+
| CONTINENT      |
| SALARY         |
| EMP_RATING     |
| MANAGER_ID (FK)|
| PROJ_ID (FK)   |
+----------------+
SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT FROM EMP_RECORD_TABLE$

SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT, EMP_RATING FROM EMP_RECORD_TABLE$
WHERE EMP_RATING < 2

SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT, EMP_RATING FROM EMP_RECORD_TABLE$
WHERE EMP_RATING > 4

SELECT EMP_ID, FIRST_NAME, LAST_NAME, GENDER, DEPT, EMP_RATING FROM EMP_RECORD_TABLE$
WHERE EMP_RATING BETWEEN 2 AND 4

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS NAME FROM EMP_RECORD_TABLE$
WHERE DEPT= 'FINANCE';

	SELECT E.EMP_ID,E.FIRST_NAME,E.LAST_NAME, COUNT(DISTINCT R.EMP_ID)AS NO_OF_REPORTERS FROM EMP_RECORD_TABLE$ E
	JOIN EMP_RECORD_TABLE$ R ON E.EMP_ID=R.MANAGER_ID
	GROUP BY E.EMP_ID,E.FIRST_NAME,E.LAST_NAME;

SELECT EMP_ID,FIRST_NAME,LAST_NAME,DEPT FROM EMP_RECORD_TABLE$
WHERE DEPT = 'FINANCE'
UNION
SELECT EMP_ID,FIRST_NAME,LAST_NAME,DEPT FROM EMP_RECORD_TABLE$
WHERE DEPT = 'HEALTHCARE';

SELECT E.EMP_ID,E.FIRST_NAME,E.LAST_NAME,E.ROLE,E.DEPT,E.EMP_RATING,
(SELECT MAX(EMP_RATING) FROM EMP_RECORD_TABLE$  WHERE DEPT=E.DEPT)AS MAX_RATING FROM EMP_RECORD_TABLE$ E
ORDER BY E.DEPT,E.EMP_ID;

SELECT MIN(SALARY) AS MIN_SALARY ,MAX(SALARY) AS MAX_SALARY ,ROLE FROM EMP_RECORD_TABLE$
GROUP BY ROLE;

SELECT EMP_ID,FIRST_NAME, LAST_NAME,EXP,
DENSE_RANK() OVER (ORDER BY EXP DESC) AS EXPERIENCE
FROM EMP_RECORD_TABLE$;	

SELECT EMP_ID,FIRST_NAME, LAST_NAME,country FROM EMP_RECORD_TABLE$
WHERE SALARY>6000
order BY COUNTRY;

SELECT * FROM EMP_RECORD_TABLE$
WHERE EXP>10;


CREATE PROCEDURE GetExperiencedEmployees
AS
BEGIN
    SET NOCOUNT ON;

    SELECT *
    FROM EMP_RECORD_TABLE$
    WHERE exp > 3;
END;


EXEC GetExperiencedEmployees;

CREATE INDEX EMPLOYEEFIRSTNAME ON EMP_RECORD_TABLE$ (FIRST_NAME);
SELECT * FROM EMP_RECORD_TABLE$
WHERE FIRST_NAME='Eric';

SELECT *,(0.05*SALARY*EMP_RATING)AS BONUS FROM EMP_RECORD_TABLE$;

SELECT COUNTRY,CONTINENT, AVG(SALARY) AS AVG_SALARY FROM EMP_RECORD_TABLE$
GROUP BY COUNTRY,CONTINENT;